# Millennium snapshot files
This notebook has some simple functions to identify the locations of Millennium snapshot files over the complex virgo_filedb volume.

In [1]:
import glob
import re
import pandas

In [2]:
def fileRank(file):
    return int(file.split(".")[-1])

def snapnum(file):
    m=re.search("_(\d\d\d).",file)
    return int(m.groups()[-1])
#    return int(m.group())

def filedbloc(file):
    file= file.replace('/home/idies/workspace/virgo_filedb/data','')
    digits=re.findall(r'\d+',file)
    return "//filedb"+digits[0]+'/data'+digits[1]+file[5:]

def volume(file):
    m=re.search('//filedb(\d\d)/data(\d\d)',file)
    return int(m.group(1))*100+int(m.group(2))

In [3]:
def snapshotsorter(f):
    return fileRank(f)

def snapdirsorter(f):
    return int(snapnum(f)*1000)+int(fileRank(f))

In [4]:
def snapshot(snapnum,sim='Millennium'):
    snap='%03d'%snapnum
    files=glob.glob('/home/idies/workspace/virgo_filedb/*/{sim}/snapdir_{snap}/snap*.*'.format(snap=snap,sim=sim)
                    , recursive=True)
    files.sort(key=snapshotsorter)
    return files

def subhaloids(snapnum,sim='Millennium'):
    snap='%03d'%snapnum
    idsfiles=glob.glob('/home/idies/workspace/virgo_filedb/*/{sim}/postproc_{snap}/sub_ids_*.*'.format(snap=snap,sim=sim)
                    , recursive=True)
    idsfiles.sort(key=snapshotsorter)
    return idsfiles

def allsnapshots(sim="Millennium"):
    files=glob.glob('/home/idies/workspace/virgo_filedb/*/{sim}/snapdir_*/snap*.*'.format(sim=sim)
                    , recursive=True)
    files.sort(key=snapdirsorter)
    return files

def allsubhaloids(sim="Millennium"):
    files=glob.glob('/home/idies/workspace/virgo_filedb/*/{sim}/postproc_*/sub_ids_*.*'.format(sim=sim)
                    , recursive=True)
    files.sort(key=snapdirsorter)
    return files

In [7]:
allfiles=snapshot(13,'Millennium')
subhaloidsfiles=subhaloids(63,'Millennium')

In [8]:
snaps=[snapnum(f) for f in allfiles]
ranks=[fileRank(f) for f in allfiles]
locations=[filedbloc(f) for f in allfiles]
volumes=[volume(f) for f in locations]

In [9]:
df=pandas.DataFrame()
df['snapnum']=snaps
df['fileRank']=ranks
df['location']=locations
df['volume']=volumes
df['simulationId']=1
df.head(36)

,snapnum,fileRank,location,volume,simulationId
0,13,0,//filedb09/data01/Millennium/snapdir_013/snap_...,901,1
1,13,1,//filedb09/data02/Millennium/snapdir_013/snap_...,902,1
2,13,2,//filedb09/data03/Millennium/snapdir_013/snap_...,903,1
3,13,3,//filedb10/data01/Millennium/snapdir_013/snap_...,1001,1
4,13,4,//filedb10/data02/Millennium/snapdir_013/snap_...,1002,1
5,13,5,//filedb10/data03/Millennium/snapdir_013/snap_...,1003,1
6,13,6,//filedb11/data01/Millennium/snapdir_013/snap_...,1101,1
7,13,7,//filedb11/data02/Millennium/snapdir_013/snap_...,1102,1
8,13,8,//filedb11/data03/Millennium/snapdir_013/snap_...,1103,1
9,13,9,//filedb12/data01/Millennium/snapdir_013/snap_...,1201,1
10,13,10,//filedb12/data02/Millennium/snapdir_013/snap_...,1202,1
11,13,11,//filedb12/data03/Millennium/snapdir_013/snap_...,1203,1
12,13,12,//filedb01/data01/Millennium/snapdir_013/snap_...,101,1
13,13,13,//filedb01/data02/Millennium/snapdir_013/snap_...,102,1
14,13,14,//filedb01/data03/Millennium/snapdir_013/snap_...,103,1
15,13,15,//filedb02/data01/Millennium/snapdir_013/snap_...,201,1
16,13,16,//filedb02/data02/Millennium/snapdir_013/snap_...,202,1
17,13,17,//filedb02/data03/Millennium/snapdir_013/snap_...,203,1
18,13,18,//filedb03/data01/Millennium/snapdir_013/snap_...,301,1
19,13,19,//filedb03/data02/Millennium/snapdir_013/snap_...,302,1
20,13,20,//filedb03/data03/Millennium/snapdir_013/snap_...,303,1
21,13,21,//filedb04/data01/Millennium/snapdir_013/snap_...,401,1
22,13,22,//filedb04/data02/Millennium/snapdir_013/snap_...,402,1
23,13,23,//filedb04/data03/Millennium/snapdir_013/snap_...,403,1
24,13,24,//filedb05/data01/Millennium/snapdir_013/snap_...,501,1
25,13,25,//filedb05/data02/Millennium/snapdir_013/snap_...,502,1
26,13,26,//filedb05/data03/Millennium/snapdir_013/snap_...,503,1
27,13,27,//filedb06/data01/Millennium/snapdir_013/snap_...,601,1
28,13,28,//filedb06/data02/Millennium/snapdir_013/snap_...,602,1
29,13,29,//filedb06/data03/Millennium/snapdir_013/snap_...,603,1
30,13,30,//filedb07/data01/Millennium/snapdir_013/snap_...,701,1
31,13,31,//filedb07/data02/Millennium/snapdir_013/snap_...,702,1
32,13,32,//filedb07/data03/Millennium/snapdir_013/snap_...,703,1
33,13,33,//filedb08/data01/Millennium/snapdir_013/snap_...,801,1
34,13,34,//filedb08/data02/Millennium/snapdir_013/snap_...,802,1
35,13,35,//filedb08/data03/Millennium/snapdir_013/snap_...,803,1

In [10]:
ids_from=['/home/idies/workspace/virgo/Millennium/procdir_{snap}/sub_ids_{snap}.{rank}'.format(snap='%03d'%snapnum(f),rank=fileRank(f)) for f in allfiles]
ids_to=['']

In [11]:
ids_from[:10]

['/home/idies/workspace/virgo/Millennium/procdir_013/sub_ids_013.0',
 '/home/idies/workspace/virgo/Millennium/procdir_013/sub_ids_013.1',
 '/home/idies/workspace/virgo/Millennium/procdir_013/sub_ids_013.2',
 '/home/idies/workspace/virgo/Millennium/procdir_013/sub_ids_013.3',
 '/home/idies/workspace/virgo/Millennium/procdir_013/sub_ids_013.4',
 '/home/idies/workspace/virgo/Millennium/procdir_013/sub_ids_013.5',
 '/home/idies/workspace/virgo/Millennium/procdir_013/sub_ids_013.6',
 '/home/idies/workspace/virgo/Millennium/procdir_013/sub_ids_013.7',
 '/home/idies/workspace/virgo/Millennium/procdir_013/sub_ids_013.8',
 '/home/idies/workspace/virgo/Millennium/procdir_013/sub_ids_013.9']